### ISSUE TITLE
hi  I want to know how to use your code in my location 

### ISSUE THREAD

**Issue by monamiiKe** [heggria/SchoolCardManager#1]
Firstly, Ｉ download your code in my pycharm
Secondly ,I　use python manage.py runserver but no index.html
Thirdly , I know you use vue to replace html but how to put it into page to show ,
I hope you can help me ! Thank you

**Comment by heggria** [comment]
You need to use npm run the vue project and it can be shown.
If you want to get the index.html and other flies，use npm run build.


There is still have a problem that you need create the database by yourself.



------------------&nbsp;Original&nbsp;------------------
